my_string = input("Введите любой текст: ")
print ("Количество символов в введенном тексте:",len(my_string))
print ("Выводим строку в верхнем регистре:",my_string.upper())
print ("Выводим строку в нижнем регистре:",my_string.lower())
print ("Выводим строку без пробелов:",my_string.replace(" ",""))
print ("Первый символ строки:",my_string[0])
print ("Последний символ строки:",my_string[-1])
